#!/usr/bin/env python3
"""Embed the board-served UI in flash; no filesystem upload is needed."""
from pathlib import Path
import argparse

root = Path(__file__).resolve().parents[1]
receiver = root / 'firmware' / 'receiver_s2'
parts = ['// Generated by scripts/embed_web_control.py; edit web/* instead.\n#pragma once\n']
for filename, symbol in [('index.html', 'CONTROL_INDEX'), ('control.js', 'CONTROL_JS'), ('style.css', 'CONTROL_CSS')]:
    source = (receiver / 'web' / filename).read_text()
    if ')SPYCAR"' in source:
        raise ValueError('Raw string delimiter occurs in source')
    parts.append(f'static const char {symbol}[] PROGMEM = R"SPYCAR({source})SPYCAR";\n')
content = '\n'.join(parts)
target = receiver / 'web_assets.h'
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
if args.check:
    if not target.exists() or target.read_text() != content:
        raise SystemExit('Web assets are stale; run python3 scripts/embed_web_control.py')
    print('Embedded web assets match source')
else:
    target.write_text(content)
    print(f'Embedded {len(content.encode())} bytes into {target.relative_to(root)}')
